# Review

In [2]:
information = {"특기":"피아노", "사는 곳":"서울"}
print(information.get("특기"))
print(information["특기"])

피아노
피아노


In [3]:
del information["특기"]
print(information)

{'사는 곳': '서울'}


In [4]:
information["나이"] = 19
print(information)

{'사는 곳': '서울', '나이': 19}


In [5]:
information.clear()
print(information)

{}


In [6]:
information = {"고향":"수원", "취미":"영화관람", "좋아하는 음식":"국수"}

for x, y in information.items():
    print(x)
    print(y)
print()

for x in information.keys():
    print(x)
print()

for y in information.values():
    print(y)

print()
print(information.items())
print(information.keys())
print(information.values())

고향
수원
취미
영화관람
좋아하는 음식
국수

고향
취미
좋아하는 음식

수원
영화관람
국수

dict_items([('고향', '수원'), ('취미', '영화관람'), ('좋아하는 음식', '국수')])
dict_keys(['고향', '취미', '좋아하는 음식'])
dict_values(['수원', '영화관람', '국수'])


In [12]:
from datetime import datetime

print(datetime.today().strftime("%Y년 %m(%h)월 %d일 %H시 %M분 %S초 a태그 내역입니다.\n"))

2023년 10(Oct)월 19일 17시 47분 14초 a태그 내역입니다.



In [1]:
# 유효성 검사
import re # python 정규 표현식 기능

reg = "^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$"
print(re.match(reg, "codelion.example@gmail.com"))
print(re.match(reg, "dkfjeiskdjf"))  # None

# 문자열 분류
input_string = "안ab녕c12하3de세f4요56"
letters = "".join(re.findall(r'[a-zA-Zㄱ-ㅎ가-힣]+', input_string))  # r: raw-string, 문자열 내의 백슬래시 문자 그대로 사용. 이스케이프 문자가 아님을 의미
numbers = "".join(re.findall(r'\d', input_string))

print(re.findall(r'[a-zA-Zㄱ-ㅎ가-힣]+', input_string))  # 리스트로 반환됨을 확인
print("문자:", letters)
print("숫자:", numbers)

<re.Match object; span=(0, 26), match='codelion.example@gmail.com'>
None
['안ab녕c', '하', 'de세f', '요']
문자: 안ab녕c하de세f요
숫자: 123456


In [16]:
my_li = [1, 5, 4, 6, 111, 111, 10, 45, 3, 2]
# extend()
my_li.extend([14, 15])
print(my_li)

# insert(index, value)
my_li.insert(1, 10)
print(my_li)

# count()
print(my_li.count(111))

# index()
print(my_li.index(111))

[1, 5, 4, 6, 111, 111, 10, 45, 3, 2, 14, 15]
[1, 10, 5, 4, 6, 111, 111, 10, 45, 3, 2, 14, 15]
2
5


- 얕은복사: 원본 데이터에 영향을 줍니다
- 깊은복사: 원본 데이터에 영향을 주지 않습니다

In [17]:
# 얕은 복사

li1 = [4, 1, 10]
li2 = li1

print(li1)
print(li2)
print()

# li2 리스트 데이터 정렬
li2.sort()

print(li2)
print(li1)

[4, 1, 10]
[4, 1, 10]

[1, 4, 10]
[1, 4, 10]


In [2]:
# 깊은 복사 
import copy 

li1 = [4, 1, 10]
li2 = copy.deepcopy(li1)  # 깊은복사

print(li1)
print(li2)
print()

li2.sort()
print(li2)
print(li1)
print()

li3 = sorted(li1)
print(li3)
print(li1)

[4, 1, 10]
[4, 1, 10]

[1, 4, 10]
[4, 1, 10]

[1, 4, 10]
[4, 1, 10]


In [1]:
# 깊은 복사
li1 = [4, 1, 10]
li2 = li1.copy()  # 깊은복사

print(li1)
print(li2)
print()

li2.sort()
print(li2)
print(li1)
print()


[4, 1, 10]
[4, 1, 10]

[1, 4, 10]
[4, 1, 10]



In [2]:
# numpy에서의 얕은 복사 깊은 복사

import numpy as np

ary = np.arange(10)
ary[0] = 100
print(ary)
ary_sub1 = ary[3:7]  # shallow copy
print(ary_sub1)
ary_sub1[:] = 77
print(ary_sub1)
print(ary)

[100   1   2   3   4   5   6   7   8   9]
[3 4 5 6]
[77 77 77 77]
[100   1   2  77  77  77  77   7   8   9]


In [3]:
ary = np.arange(10)
ary_sub2 = ary[3:7].copy()  # 복사의 방식, deep copy
print(ary_sub2)
ary_sub2[:] = 88
print(ary_sub2)
print(ary)

[3 4 5 6]
[88 88 88 88]
[0 1 2 3 4 5 6 7 8 9]


In [19]:
# 리스트와 튜플의 저장공간 차이 비교

import sys

li = [1, 2, 3]
tp = (1, 2, 3)

print(sys.getsizeof(li))
print(sys.getsizeof(tp))

80
64


In [5]:
#list
city = ["seoul", "daegu", "busan"]
pop = [500, 300, 200]

# zip(list1, list2)
data = dict(zip(city, pop))
print(data)

data = list(zip(city, pop))
print(data)
print(type(data[0]))

{'seoul': 500, 'daegu': 300, 'busan': 200}
[('seoul', 500), ('daegu', 300), ('busan', 200)]
<class 'tuple'>


[연산자의 종류와 우선순위]
- 괄호: () (괄호 안의 표현식이 가장 먼저)
- 지수 연산자: **
- 단항 연산자: -(음수), +(양수), ~(반전)
- 곱셈, 나눗셈, 나머지 연산자 : *, /, //, %
- 덧셈, 뺄셈 연산자 : +, -
- 비교 연산자: <, >, <=, >=, ==, !=
- 논리 연산자: and, or, not
- 멤버 연산자: in, not in
- 항등 연산자: is, is not
- 할당 연산자: +=, -=, *=, /=, //=, %=, **=
- 삼항 조건 연산자: if-else

In [21]:
# 삼항 연산자
money = 10000

print("taxi") if money >= 10000 else print("walk")

taxi


In [13]:
import random

print(random.sample([1, 2, 3, 4, 5, 6], 3))
print(random.sample(range(1, 46), 3))

[6, 2, 5]
[24, 28, 5]


In [14]:
import time

start = time.time()
### 프로그램 작성 ###
end = time.time()

print("프로그램 실행 시간: ", end-start)

프로그램 실행 시간:  0.0


In [15]:
# 조건이 있는 리스트 컴프리헨션

li1 = [1, 2, 3, 4, 5]
li2 = [i * 2 for i in li1 if i % 2 == 1]
li2

[2, 6, 10]

In [1]:
# zip

li1 = [1, 2, 3]
li2 = [4, 5, 6]

for i, k in li1, li2:
    print(i, k)

ValueError: too many values to unpack (expected 2)

In [2]:
for i, k in zip(li1, li2):
    print(i, k)

1 4
2 5
3 6


In [3]:
# strip

temp = "/2019/30/20/"
temp = temp.strip('/')  # strip은 양쪽 끝 문자를 제거
print(temp)

2019/30/20


In [5]:
# 만약 모든 /를 없애고 싶다면 replace 문자

temp = "/2019/30/20/"
temp = temp.replace('/', '')
print(temp)

20193020
