# Review

In [2]:
information = {"특기":"피아노", "사는 곳":"서울"}
print(information.get("특기"))
print(information["특기"])

피아노
피아노


In [3]:
del information["특기"]
print(information)

{'사는 곳': '서울'}


In [4]:
information["나이"] = 19
print(information)

{'사는 곳': '서울', '나이': 19}


In [5]:
information.clear()
print(information)

{}


In [6]:
information = {"고향":"수원", "취미":"영화관람", "좋아하는 음식":"국수"}

for x, y in information.items():
    print(x)
    print(y)
print()

for x in information.keys():
    print(x)
print()

for y in information.values():
    print(y)

print()
print(information.items())
print(information.keys())
print(information.values())

고향
수원
취미
영화관람
좋아하는 음식
국수

고향
취미
좋아하는 음식

수원
영화관람
국수

dict_items([('고향', '수원'), ('취미', '영화관람'), ('좋아하는 음식', '국수')])
dict_keys(['고향', '취미', '좋아하는 음식'])
dict_values(['수원', '영화관람', '국수'])


In [12]:
from datetime import datetime

print(datetime.today().strftime("%Y년 %m(%h)월 %d일 %H시 %M분 %S초 a태그 내역입니다.\n"))

2023년 10(Oct)월 19일 17시 47분 14초 a태그 내역입니다.



In [1]:
# 유효성 검사
import re # python 정규 표현식 기능

reg = "^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$"
print(re.match(reg, "codelion.example@gmail.com"))
print(re.match(reg, "dkfjeiskdjf"))  # None

# 문자열 분류
input_string = "안ab녕c12하3de세f4요56"
letters = "".join(re.findall(r'[a-zA-Zㄱ-ㅎ가-힣]+', input_string))  # r: raw-string, 문자열 내의 백슬래시 문자 그대로 사용. 이스케이프 문자가 아님을 의미
numbers = "".join(re.findall(r'\d', input_string))

print(re.findall(r'[a-zA-Zㄱ-ㅎ가-힣]+', input_string))  # 리스트로 반환됨을 확인
print("문자:", letters)
print("숫자:", numbers)

<re.Match object; span=(0, 26), match='codelion.example@gmail.com'>
None
['안ab녕c', '하', 'de세f', '요']
문자: 안ab녕c하de세f요
숫자: 123456


In [16]:
my_li = [1, 5, 4, 6, 111, 111, 10, 45, 3, 2]
# extend()
my_li.extend([14, 15])
print(my_li)

# insert(index, value)
my_li.insert(1, 10)
print(my_li)

# count()
print(my_li.count(111))

# index()
print(my_li.index(111))

[1, 5, 4, 6, 111, 111, 10, 45, 3, 2, 14, 15]
[1, 10, 5, 4, 6, 111, 111, 10, 45, 3, 2, 14, 15]
2
5


- 얕은복사: 원본 데이터에 영향을 줍니다
- 깊은복사: 원본 데이터에 영향을 주지 않습니다

In [17]:
# 얕은 복사

li1 = [4, 1, 10]
li2 = li1

print(li1)
print(li2)
print()

# li2 리스트 데이터 정렬
li2.sort()

print(li2)
print(li1)

[4, 1, 10]
[4, 1, 10]

[1, 4, 10]
[1, 4, 10]


In [2]:
# 깊은 복사 
import copy 

li1 = [4, 1, 10]
li2 = copy.deepcopy(li1)  # 깊은복사

print(li1)
print(li2)
print()

li2.sort()
print(li2)
print(li1)
print()

li3 = sorted(li1)
print(li3)
print(li1)

[4, 1, 10]
[4, 1, 10]

[1, 4, 10]
[4, 1, 10]

[1, 4, 10]
[4, 1, 10]


In [1]:
# 깊은 복사
li1 = [4, 1, 10]
li2 = li1.copy()  # 깊은복사

print(li1)
print(li2)
print()

li2.sort()
print(li2)
print(li1)
print()


[4, 1, 10]
[4, 1, 10]

[1, 4, 10]
[4, 1, 10]



In [2]:
# numpy에서의 얕은 복사 깊은 복사

import numpy as np

ary = np.arange(10)
ary[0] = 100
print(ary)
ary_sub1 = ary[3:7]  # shallow copy
print(ary_sub1)
ary_sub1[:] = 77
print(ary_sub1)
print(ary)

[100   1   2   3   4   5   6   7   8   9]
[3 4 5 6]
[77 77 77 77]
[100   1   2  77  77  77  77   7   8   9]


In [3]:
ary = np.arange(10)
ary_sub2 = ary[3:7].copy()  # 복사의 방식, deep copy
print(ary_sub2)
ary_sub2[:] = 88
print(ary_sub2)
print(ary)

[3 4 5 6]
[88 88 88 88]
[0 1 2 3 4 5 6 7 8 9]


In [19]:
# 리스트와 튜플의 저장공간 차이 비교

import sys

li = [1, 2, 3]
tp = (1, 2, 3)

print(sys.getsizeof(li))
print(sys.getsizeof(tp))

80
64


In [5]:
#list
city = ["seoul", "daegu", "busan"]
pop = [500, 300, 200]

# zip(list1, list2)
data = dict(zip(city, pop))
print(data)

data = list(zip(city, pop))
print(data)
print(type(data[0]))

{'seoul': 500, 'daegu': 300, 'busan': 200}
[('seoul', 500), ('daegu', 300), ('busan', 200)]
<class 'tuple'>


[연산자의 종류와 우선순위]
- 괄호: () (괄호 안의 표현식이 가장 먼저)
- 지수 연산자: **
- 단항 연산자: -(음수), +(양수), ~(반전)
- 곱셈, 나눗셈, 나머지 연산자 : *, /, //, %
- 덧셈, 뺄셈 연산자 : +, -
- 비교 연산자: <, >, <=, >=, ==, !=
- 논리 연산자: and, or, not
- 멤버 연산자: in, not in
- 항등 연산자: is, is not
- 할당 연산자: +=, -=, *=, /=, //=, %=, **=
- 삼항 조건 연산자: if-else

In [21]:
# 삼항 연산자
money = 10000

print("taxi") if money >= 10000 else print("walk")

taxi


In [13]:
import random

print(random.sample([1, 2, 3, 4, 5, 6], 3))
print(random.sample(range(1, 46), 3))

[6, 2, 5]
[24, 28, 5]


In [14]:
import time

start = time.time()
### 프로그램 작성 ###
end = time.time()

print("프로그램 실행 시간: ", end-start)

프로그램 실행 시간:  0.0


In [15]:
# 조건이 있는 리스트 컴프리헨션

li1 = [1, 2, 3, 4, 5]
li2 = [i * 2 for i in li1 if i % 2 == 1]
li2

[2, 6, 10]

In [1]:
# zip

li1 = [1, 2, 3]
li2 = [4, 5, 6]

for i, k in li1, li2:
    print(i, k)

ValueError: too many values to unpack (expected 2)

In [2]:
for i, k in zip(li1, li2):
    print(i, k)

1 4
2 5
3 6


In [3]:
# strip

temp = "/2019/30/20/"
temp = temp.strip('/')  # strip은 양쪽 끝 문자를 제거
print(temp)

2019/30/20


In [4]:
# 만약 모든 /를 없애고 싶다면 replace 문자

temp = "/2019/30/20"
temp = temp.replace('/', '')
print(temp)

/2019%30$20


In [5]:
# 여러 문자를 대체하고 싶을 때

original_string = "This is a string with /, %, and $ symbols."
characters_to_replace = "/%$"
replacement_character = "@"

for char in characters_to_replace:  # 대체하고 싶은 모든 문자를 담은 문자열을 반목문으로 접근
    original_string = original_string.replace(char, replacement_character)

print(original_string)

This is a string with @, @, and @ symbols.


In [6]:
# 정규 표현식으로 여러 문자를 대체

import re

original_string = "This is a string with /, %, and $ symbols."
pattern = r"[/%$]"
replacement_character = "@"

new_string = re.sub(pattern, replacement_character, original_string)
print(new_string)

This is a string with @, @, and @ symbols.


In [10]:
# enumerate

temp_dict = {"data1": 1, "data2": 2, "data3": 3}

for data in enumerate(temp_dict):
    print(data)

for idx, data in enumerate(temp_dict):
    print(idx, data)

(0, 'data1')
(1, 'data2')
(2, 'data3')
0 data1
1 data2
2 data3


In [13]:
def my_add(num1, num2=10):  # parameter, default parameter
    print(num1 + num2)
    
my_add(1, 2)  # argument
my_add(1)
my_add(1, num2 = 30)  # keyword argument

3
11


In [14]:
#  매개변수 힌트와 docstring

def my_sum(num1 : int, num2 : int, num3 : int) -> int:
    """
    이 함수는 숫자 3개를 입력 받습니다.
    입력받은 정수 데이터 3개를 합산합니다.
    """
    return num1 + num2 + num3

In [15]:
help(my_sum)

Help on function my_sum in module __main__:

my_sum(num1: int, num2: int, num3: int) -> int
    이 함수는 숫자 3개를 입력 받습니다.
    입력받은 정수 데이터 3개를 합산합니다.



In [16]:
def my_print_func_args(*args):  # *parameter
    print(args)
    
my_print_func_args("text")  # tuple container로 반환하면서 형식이 (data,)로 지정되어 나옴
my_print_func_args(1)
my_print_func_args("text", 1, 2, 3, 4, [1, 2, 3])

('text',)
(1,)
('text', 1, 2, 3, 4, [1, 2, 3])


In [17]:
# unpacking

ls = [1, 2, 3]  # itreable

print(ls)
print(*ls)  # *iterable, 하나씩 뽑아와서 출력

[1, 2, 3]
1 2 3


In [19]:
# keyword argument unpacking

def func_kwargs(**kwargs):
    print(kwargs)

func_kwargs(name="codelion", age=5)

{'name': 'codelion', 'age': 5}


In [21]:
# lambda

def calc(func, num1, num2):
    return func(num1, num2)

def plus(num1, num2):
    return num1 + num2

print(calc(plus, 1, 2))

print(calc(lambda num1, num2: num1 - num2, 1, 2)) 

3
-1


In [23]:
# dir()
# 클래스가 가진 속성과 메서드를 확인합니다
text = "python"
text.upper()
dir(text)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [25]:
class MyAdd(int):
    def __init__(self, value):
        # int class 상속
        super().__init__()
        self.value = value
    
    # int 클래스가 가진 __add__ 메서드에 오버라이딩
    def __add__(self, other):
        # 데이터 타입이 같은 경우에만 연산 수행 (해당 클래스의 인스턴스인지 확인)
        if isinstance(other, MyAdd):
            return MyAdd(self.value - other)
        else:
            raise TypeError("MyAdd로 만든 데이터만 사용해주세요.")

In [26]:
num1 = MyAdd(5)
num2 = MyAdd(10)

# 오버라이딩한 __add__ 메서드 호출
print(num1.__add__(num2))  # MyAdd 클래스의 오버라이딩 한 더하기 연산 사용
print(MyAdd(10) + MyAdd(5))  # MyAdd 클래스의 오버라이딩 한 더하기 연산사용
print(MyAdd(5) - MyAdd(5))  # 상속받은(부모클래스)가 가진 빼기 연산을 사용
print(MyAdd(5) - 5)  # 상속받은(부모클래스)가 가진 빼기 연산을 사용
print(MyAdd(20).__add__(MyAdd(10)))

print(MyAdd(5) + 5)  # 타입에러 발생! MyAdd 더하기 연산 사용

-5
5
0
0
10


TypeError: MyAdd로 만든 데이터만 사용해주세요.

In [28]:
# is-a (상속 관계)

class Animal:
    
    def __init__(self, name):
        self.name = name
        
    def speak(self):
        pass
    
class Dog(Animal):
    def speak(self):
        return f"{self.name}가 왈왈 짖습니다."
    
class Cat(Animal):
    def speak(self):
        return f"{self.name}가 야옹야옹 웁니다."

In [27]:
# has-a (포함 관계)

class Car:
    
    def __init__(self):
        self.engine = Engine()
    
    def drive(self):
        self.engine.start()
    
class Engine:
    def start(self):
        pass

In [29]:
class Person:
    
    def __init__(self, name):
        self.name = name
        self.notebook = None
    
    def acquire_notebook(self, notebook):
        self.notebook = notebook
        print(f"{self.name}이/가 {self.notebook.brand}을 얻었습니다.")
        
class Notebook:
    
    def __init__(self, brand):
        self.brand = brand
        
person = Person("codelion")
notebook = Notebook("macbook")

person.acquire_notebook(notebook)

codelion이/가 macbook을 얻었습니다.


In [ ]:
# 파이썬 내장 예외 처리
# ZeroDivisionError

try:
    result = 10 / 0
    print(result)
except ZeroDivisionError as e:  # (error name) as (저장): e에 저장되어서 어떤 에러인지 출력됨
    print("error!")
    print(e)

In [ ]:
# 파이썬 내장 예외 처리
# ValueError 처리

try:
    num = int("abc")
except ValueError as e:
    print(e)

invalid literal for int() with base 10: 'abc'


In [ ]:
# 파이썬 내장 예외 처리
# FileNotFoundError 처리

# !conda install -y pandas
import pandas as pd

try:
    data = pd.read_csv("data.csv")
except FileNotFoundError as e:
    print(e)

[Errno 2] No such file or directory: 'data.csv'


In [ ]:
# 파이썬 내장 예외 처리
# data.csv파일 추가한 후

try:
    data = pd.read_csv("data.csv")
except FileNotFoundError as e:
    print(e)

In [ ]:
data

Empty DataFrame
Columns: [안녕하세요 저는 사자입니다]
Index: []

In [30]:
# 사용자 정의 예외 클래스
# raise

class OutOfRangeError(Exception):

    def __init__(self):
        super().__init__("안내한 범위를 벗어났습니다.")
        
try:
    num =  int(input("1부터 10사이의 숫자를 입력하세요. "))
    if (num < 1) or (num > 10):
        raise OutOfRangeError()  # 샤용자 정의 예외 발생, except 구문으로 이동
        print("raise 아래 있는 코드는 실행되지 않습니다.")
    else:
        print(f"입력한 숫자는 {num} 입니다.")
except Exception as e:  # Exception as e: 내가 정의한 상속 클래스
    print('='*50)
    print("raise 에서 발생한 에러는 except 구문으로 넘어옵니다.")
    print(e)

raise 에서 발생한 에러는 except 구문으로 넘어옵니다.
안내한 범위를 벗어났습니다.


In [31]:
try:
    num = int(input("정수를 입력해주세요 : "))
except ValueError as e:  # 입력한 데이터 타입이 정수가 아닌 경우 예외 발생
    print(e)
else:  # try 코드에서 예외가 발생하지 않은 경우 실행
    print()
    print("else 문 코드 실행")
    print(num)
finally:
    print()
    print("finally!! 나는 무조건 실행합니다!!!!")


else 문 코드 실행
1

finally!! 나는 무조건 실행합니다!!!!
